<?php

namespace Eapp\BlogBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function getArticles()
	  {
	    $query = $this->createQueryBuilder('a')
	      ->orderBy('a.published', 'DESC')
	      ->getQuery()
	      ->setMaxResults(10)
	    ;

	    return $query->getResult();
	  }
}
